# Write a Python program to draw a house using Turtle.
import turtle as t

t.speed(3)
t.penup()
t.goto(-100, -100)
t.pendown()
t.color("blue")
t.begin_fill()
for _ in range(2):
    t.forward(200)
    t.left(90)
    t.forward(150)
    t.left(90)
t.end_fill()
t.penup()
t.goto(-100, 50)
t.pendown()
t.color("red")
t.begin_fill()
t.goto(0, 150)
t.goto(100, 50)
t.goto(-100, 50)
t.end_fill()
t.done()